webtalk_init -webtalk_dir /afs/athena.mit.edu/user/c/o/cordone/Desktop/6.111/FPGA-ball-and-plate/FPGA-ball-and-plate.sim/sim_1/behav/xsim.dir/stage3_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 10 21:11:44 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211027694_1777504441_210661626_020" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cdaf8ac61a2c51b0b816a53f7ad1746a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b88da8e353b4e9987c87d8e5f0027fd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4690S CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3693.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "38" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "2128 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "206 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "4670" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2597" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "357" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "9.52_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "675980_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1201874190 -regid "211027694_1777504441_210661626_020" -xml /afs/athena.mit.edu/user/c/o/cordone/Desktop/6.111/FPGA-ball-and-plate/FPGA-ball-and-plate.sim/sim_1/behav/xsim.dir/stage3_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /afs/athena.mit.edu/user/c/o/cordone/Desktop/6.111/FPGA-ball-and-plate/FPGA-ball-and-plate.sim/sim_1/behav/xsim.dir/stage3_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /afs/athena.mit.edu/user/c/o/cordone/Desktop/6.111/FPGA-ball-and-plate/FPGA-ball-and-plate.sim/sim_1/behav/xsim.dir/stage3_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
